spring.application.name=bancoudea
server.port=${PORT:8080}

# Datos de conexión: usarán Render si existe la variable, si no, usarán tu MySQL local
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/bancoudea?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# LÍNEAS ELIMINADAS O COMENTADAS:
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true

spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json
